services:
    minsal_sipernes_actividad.admin.enf_ctl_actividad:
        class: Minsal\Sipernes\ActividadBundle\Admin\EnfCtlActividadAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfCtlActividad, MinsalSipernesActividadBundle:EnfCtlActividadAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: ACT-1-Actividad, label: Catálogo tipo de actividades}

    minsal_sipernes_actividad.admin.enf_ctl_subactividad:
        class: Minsal\Sipernes\ActividadBundle\Admin\EnfCtlSubactividadAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfCtlSubactividad, MinsalSipernesActividadBundle:EnfCtlSubactividadAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: ACT-1-Actividad, label: Catálogo de actividades}

    minsal_sipernes_actividad.admin.enf_mtl_actividad:
        class: Minsal\Sipernes\ActividadBundle\Admin\EnfMtlActividadAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfMtlActividad, MinsalSipernesActividadBundle:EnfMtlActividadAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: ACT-1-Actividad, label: Actividad realizada a paciente }

    minsal_sipernes_actividad.admin.enf_ctl_financiamiento:
        class: Minsal\Sipernes\ActividadBundle\Admin\EnfCtlFinanciamientoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfCtlFinanciamiento, MinsalSipernesActividadBundle:EnfCtlFinanciamientoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CPC-1-Capacitacion, label: Empresas de financiamiento}

    minsal_sipernes_actividad.admin.enf_mtl_capacitacion:
        class: Minsal\Sipernes\ActividadBundle\Admin\EnfMtlCapacitacionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfMtlCapacitacion, MinsalSipernesActividadBundle:EnfMtlCapacitacionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: CPC-1-Capacitacion, label: Capacitaciones impartidas}
