services:
    minsal_sipernes_aplicaciones.admin.enf_esquema_vac:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfEsquemaVacAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfEsquemaVac, MinsalSipernesAplicacionesBundle:EnfEsquemaVacAdmin ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: APL-1-Aplicacion, label: Catálogo fase de aplicación}

    minsal_sipernes_aplicaciones.admin.enf_tipo_esquema_vac:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfTipoEsquemaVacAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTipoEsquemaVac, MinsalSipernesAplicacionesBundle:EnfTipoEsquemaVacAdmin] 
        tags:
            - {name: sonata.admin, manager_type: orm, group: APL-1-Aplicacion, label: Catálogo de aplicación}

    minsal_sipernes_aplicaciones.admin.enf_ctl_tipo_componente:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfCtlTipoComponenteAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfCtlTipoComponente,MinsalSipernesAplicacionesBundle:EnfCtlTipoComponenteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IVT-1-Inventario, label: Catálogo tipo componentes}

    minsal_sipernes_aplicaciones.admin.enf_ctl_mov_inventario:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfCtlMovInventarioAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfCtlMovInventario, MinsalSipernesAplicacionesBundle:EnfCtlMovInventarioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IVT-1-Inventario, label: Catálogo movimiento en inventario}

    minsal_sipernes_aplicaciones.admin.enf_inventario:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfInventarioAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfInventario, MinsalSipernesAplicacionesBundle:EnfInventarioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IVT-1-Inventario, label: Inventario}

    minsal_sipernes_aplicaciones.admin.enf_componente:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfComponenteAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfComponente, MinsalSipernesAplicacionesBundle:EnfComponenteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IVT-1-Inventario, label: Componentes}

    minsal_sipernes_aplicaciones.admin.enf_dosis_esquema_vac:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfDosisEsquemaVacAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfDosisEsquemaVac, MinsalSipernesAplicacionesBundle:EnfDosisEsquemaVacAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: APL-1-Aplicacion, label: Aplicación }

    minsal_sipernes_aplicaciones.admin.enf_mov_inventario:
        class: Minsal\Sipernes\AplicacionesBundle\Admin\EnfMovInventarioAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfMovInventario, MinsalSipernesAplicacionesBundle:EnfMovInventarioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: IVT-1-Inventario, label: Movimiento de inventario}
