services:
    minsal_sipernes_reportes.admin.enf_historico_capacitacion:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHistoricoCapacitacionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHistoricoCapacitacion, MinsalSipernesReportesBundle:ReportePrueba1]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Comparativo de pacientes atendidos versus diagnosticos de enfermeria}

    minsal_sipernes_reportes.admin.enf_historico_actividad:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHistoricoActividadAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHistoricoActividad, MinsalSipernesReportesBundle:ReportePrueba2]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Consolidado de Actividades Realizadas}

    minsal_sipernes_reportes.admin.enf_historico_intervencion:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHistoricoIntervencionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHistoricoIntervencion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Comparativo de micronutrientes aplicados versus planificados}

    minsal_sipernes_reportes.admin.enf_hitorico_diagnostico:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHitoricoDiagnosticoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHitoricoDiagnostico, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Consolidado de Anotaciones de Enfermería a Pacientes}

    minsal_sipernes_reportes.admin.enf_historico_dosis:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHistoricoDosisAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHistoricoDosis, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Comparativo de vacunación versus planificadas}

    minsal_sipernes_reportes.admin.enf_historico_nota:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHistoricoNotaAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHistoricoNota, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Consolidado de Diagnósticos Efectuados por el Personal de Enfermería a Pacientes Hospitalarios}

    minsal_sipernes_reportes.admin.enf_historico_inventario:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfHistoricoInventarioAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfHistoricoInventario, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Informe diario de anotaciones de enfermería por paciente}

    minsal_sipernes_reportes.admin.enf_traza_capacitacion:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaCapacitacionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaCapacitacion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Consolidado diario de diagnósticos realizados por el personal de enfermería}

    minsal_sipernes_reportes.admin.enf_traza_intervencion:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaIntervencionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaIntervencion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Consolidado diario de aplicación de micronutrientes}

    minsal_sipernes_reportes.admin.enf_traza_diagnostico:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaDiagnosticoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaDiagnostico, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Consolidado diario de vacunación}

    minsal_sipernes_reportes.admin.enf_traza_actividad:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaActividadAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaActividad, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte de registros mensuales de producción}

    minsal_sipernes_reportes.admin.enf_traza_dosis:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaDosisAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaDosis, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Comparativo de micronutrientes aplicados}

    minsal_sipernes_reportes.admin.enf_traza_nota:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaNotaAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaNota, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 14}

    minsal_sipernes_reportes.admin.enf_traza_inventario:
        class: Minsal\Sipernes\ReportesBundle\Admin\EnfTrazaInventarioAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\EnfTrazaInventario, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 15}

    minsal_sipernes_reportes.admin.ctl_tipo_atencion:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlTipoAtencionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlTipoAtencion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 16}

    minsal_sipernes_reportes.admin.ctl_municipio:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlMunicipioAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlMunicipio, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 17}

    minsal_sipernes_reportes.admin.ctl_pais:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlPaisAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlPais, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 18}

    minsal_sipernes_reportes.admin.ctl_departamento:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlDepartamentoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlDepartamento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 19}

    minsal_sipernes_reportes.admin.ctl_area_atencion:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlAreaAtencionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlAreaAtencion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 20}

    minsal_sipernes_reportes.admin.ctl_atencion:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlAtencionAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlAtencion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 21}

    minsal_sipernes_reportes.admin.ctl_establecimiento:
        class: Minsal\Sipernes\ReportesBundle\Admin\CtlEstablecimientoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\CtlEstablecimiento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 22}

    minsal_sipernes_reportes.admin.mnt_paciente:
        class: Minsal\Sipernes\ReportesBundle\Admin\MntPacienteAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\MntPaciente, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 23}

    minsal_sipernes_reportes.admin.mnt_expediente:
        class: Minsal\Sipernes\ReportesBundle\Admin\MntExpedienteAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\MntExpediente, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 24}

    minsal_sipernes_reportes.admin.mnt_empleado:
        class: Minsal\Sipernes\ReportesBundle\Admin\MntEmpleadoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\MntEmpleado, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 25}

    minsal_sipernes_reportes.admin.fos_user_user:
        class: Minsal\Sipernes\ReportesBundle\Admin\FosUserUserAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\FosUserUser, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 26}

    minsal_sipernes_reportes.admin.sec_ingreso:
        class: Minsal\Sipernes\ReportesBundle\Admin\SecIngresoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\SecIngreso, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 27}

    minsal_sipernes_reportes.admin.fos_user_group:
        class: Minsal\Sipernes\ReportesBundle\Admin\FosUserGroupAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\FosUserGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 28}

    minsal_sipernes_reportes.admin.mnt_expediente_establecimiento:
        class: Minsal\Sipernes\ReportesBundle\Admin\MntExpedienteEstablecimientoAdmin
        arguments: [~, Minsal\SipernesBundle\Entity\MntExpedienteEstablecimiento, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: RPT-1-ReportePrueba1, label: Reporte Prueba 29}
